### ISSUE TITLE
More elaborate README.md

### ISSUE THREAD

**Issue by luzpaz** [jptned/3DGuitar#2]
Suggestions to include:  
- [x] screenshots  
- [x] add a more informative summary,  
- [x] move forum link in to README  
- [ ] requirments (is it compatible with FC 0.17 dev?),  
- [ ] add to [FreeCAD-addons](https://github.com/FreeCAD/FreeCAD-addons) as a downloadable Workbench

**Comment by jptned** [comment]
As this module is not being maintained, I can not guaranty that it works in versions higher than 0.14. Therefor, I will not add it to the FreeCAD addons.

**Comment by luzpaz** [comment]
Makes sense! Thanks for all your work. One last thing.. can you change the repo summary? Right now you have a link to the forums there
NVM.. you did it already!

**Comment by jptned** [comment]
I've already added a short summary. The link to the forums is in the website field.
